language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - gem install scss-lint
  - npm install -g webpack yarn
  - yarn -V
install:
  - yarn install
before_script:
  - webpack
script:
  - npm test
  - npm run lint
